name: 'PyUp Safety'

on: [push, pull_request]

jobs:
  security:

    # runs-on: ubuntu-latest
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: 3.10
    - name: Run safety from PyUp
      run: |
        python -m pip install --upgrade pip
        cd ./Python
        python3 setup.py install
        pip3 freeze > requirements.txt
        pip3 install safety
        safety check -r requirements.txt

